# Generated by Django 4.1.7 on 2023-03-17 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationship",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Relationship",
        ),
    ]
