# Generated by Django 4.1.7 on 2023-03-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
    ]
