# Generated by Django 3.2.18 on 2023-03-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20230311_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='description',
            new_name='message',
        ),
    ]
